### ISSUE TITLE
Alias "pip install" to "guarddog"

### ISSUE THREAD

**Issue by christophetd** [DataDog/guarddog#22]
Just a random idea I had:

As a: developer
I want to: automatically run pysecurity on every package I install
and that: the installation fails if the package is dangerous
so that: I don't install malicious packages

The idea would be to document a way to have an alias that runs pysecurity, then pip install, and fails if the package is deemed "risky".

Sample usage:

```
$ securepip install mypackage
Scanning mypackage with pysecurity...
No malicious behavior found, proceeding with pip install
```

Implementation: the easiest would be to provide a bash function one could add to their `.bashrc`

**Comment by quantumpacket** [comment]
How would we get this to work with different package managers like Poetry? According to what I could find Poetry [adds extra args](https://github.com/python-poetry/poetry/blob/master/src/poetry/utils/pip.py#L28-L35) when running pip commands, which could break if an alias was added for pip without the proper args.

---

This was what I plan on doing for Poetry:

1. Run `poetry lock` to generate a lock file without installing.
2. Run `poetry export -o requirements.txt` to convert lockfile format.
3. Run `pip download -r requirements.txt` to download the locked packages.
4. Scan each package with GuardDog and do stuff...
5. If all is good then run `pip install <package-name>` for each downloaded package.

If I'm correct, this should scan all packages that would be installed for a project including any dependency?

**Comment by christophetd** [comment]
Another way would be to have a "proxy command" directly in GuardDog that emulates the right behavior, e.g. `guarddog poetry xxx` and `guarddog pip install`

**Comment by andrewkrug** [comment]
+1 for adding direct support for the discovery and parsing of manifests that aren't just requirements.txt (like Poetry)

**Comment by vdeturckheim** [comment]
For reference, Socket security just released a similar thing for npm. I really really like the concept here!

**Comment by sobregosodd** [comment]
Closing this issue, since https://github.com/DataDog/supply-chain-firewall/ was introduced to do this.
Is not the same, since scfw works on known malicious items rather than live data, but further extending scfw is being considered
