### ISSUE TITLE
Ignore benign setup() invocations in cmd-overwrite

### ISSUE THREAD

**Issue by d-niu** [DataDog/guarddog#220]
It is a common pattern to use [setuptools's](https://setuptools.pypa.io/en/latest/userguide/extension.html) setup() override to change the behavior of the default set up invocation. However, many packages [don't use the entry points feature of setuptools setup() or call any additional code](https://github.com/tchlux/tlux/blob/main/setup.py#L38-L55). It is fairly obvious when setup() [is calling other code](https://github.com/learning-at-home/hivemind/blob/master/setup.py#L146-L187). 

We should modify cmd-overwrite to be more granular when scanning for setup() in setup.py.

**Comment by sobregosodd** [comment]
`cmd-overwrite` requires the use of `cmdclass` to further execute extra code at installation time.
closing this one
