### ISSUE TITLE
Troubleshoot false negative on exec base64

### ISSUE THREAD

**Issue by christophetd** [DataDog/guarddog#242]
Sample: libidee/0.1 (triage UI http://localhost:3000/package/pypi/libidee/0.1)

![image](https://github.com/DataDog/guarddog/assets/136675/e6b4ac9c-cd85-4189-9d74-4794ebde74e2)

![image](https://github.com/DataDog/guarddog/assets/136675/2f448110-bcb2-4f58-b131-dcff5b6a9c8e)

Expected to match https://github.com/DataDog/guarddog/blob/main/guarddog/analyzer/sourcecode/exec-base64.yml

**Comment by zmallen** [comment]
Removed the large string in the beginning and kept the smaller base64 decode, and it caught the rule above.

I think this is semgrep erroring out and it might be an interesting metadata heuristic
