### ISSUE TITLE
Some rules failing

### ISSUE THREAD

**Issue by SCH227** [DataDog/guarddog#258]
When running pypi scan, `potentially_compromised_email_domain` and `repository_integrity_mismatch` rules _sometimes_ fail with the following error messages:

![image](https://github.com/DataDog/guarddog/assets/69127692/4b3c4fd5-e747-4e01-bc48-bdcbea31487f)
![image](https://github.com/DataDog/guarddog/assets/69127692/5869f61c-8cf0-44b8-9555-c7118bf363a4)

Tested on `Guarddog 1.1.3` and `1.1.4` with `Python 3.11.2` and a fresh installation using `Python 3.10.2`.

**Comment by christophetd** [comment]
Thanks for reporting! I'm able to reproduce it with `orzo`

**Comment by christophetd** [comment]
Fixed in #268
