### ISSUE TITLE
GuardDog fails if package version is not in PyPi

### ISSUE THREAD

**Issue by AngellusMortis** [DataDog/guarddog#262]
## Background (How)

We have an internal PyPi repo that we install private packages from. We also accidentally named one of our packages the same as a no named PyPi package with very little downloads. Our PyPI index prioritizes our internal packages so this is not a problem for us.

However, this means we have version numbers for a package that exists on PyPi, but _does not have that version number_. 

## Reproduction

Below is a simple example requrements.txt that will reproduce the issue:

`requests==2.30.0` is the real version
```
requests==2.30.10
```

```bash
$ guarddog pypi verify requirements.txt
/home/app/.local/lib/python3.10/site-packages/future/standard_library/__init__.py:65: DeprecationWarning: the imp module is deprecated in favour of importlib and slated for removal in Python 3.12; see the module's documentation for alternative uses
  import imp
Scanning using at most 20 parallel worker threads
Received 
```

**Comment by christophetd** [comment]
Thanks for sharing, looks like the output you shared is incomplete?

**Comment by AngellusMortis** [comment]
Nope. That is actually what it does.
