### ISSUE TITLE
Reduce the sensitivity of "npm_metadata_mismatch" check

### ISSUE THREAD

**Issue by juliendoutre** [DataDog/guarddog#330]
There are way too many NPM packages triggering this check when the mismatch is completely benign.

Only checking for mismatch on the scripts field in the NPM metadata should be enough to block [the NPM manifest confusion attack](https://jfrog.com/blog/addressing-the-npm-manifest-confusion-vulnerability/), while causing way less (zero?) false positive.

**Comment by cedricvanrompay-datadog** [comment]
@juliendoutre should this issue be closed now that https://github.com/DataDog/guarddog/pull/331 is merged?
