### ISSUE TITLE
Typo in GUARDDOG_PARALLELISIM environment variable name

### ISSUE THREAD

**Issue by strathos** [DataDog/guarddog#375]
Guarddog checks for the environment variable `GUARDDOG_PARALLELISM` but then reads the value from `GUARDDOG_PARALLELISIM` ("SM" vs. "SIM"): https://github.com/DataDog/guarddog/blob/main/guarddog/scanners/scanner.py#L94-L95

They should be the same, right? As a work-around I just export both with same value.

**Comment by christophetd** [comment]
Hi there! That's indeed a typo, thanks for reporting. Will fix it shortly
