### ISSUE TITLE
Use Semgrep join and extract mode to make rules more robust

### ISSUE THREAD

**Issue by enelli** [DataDog/guarddog#41]
### Join and Extract Mode Documentation
https://semgrep.dev/docs/experiments/join-mode/recursive-joins/
https://semgrep.dev/docs/experiments/extract-mode/

### Ideas for Improvements
Join mode could allow us to create a collection of similar commands to reuse in all our rules, kind of like how CodeQL has an all encompassing user-input command. Extract mode could help us detect bash commands hidden in exec/eval/os.system/etc. commands instead of broadly detecting the calling function.

Note: For now, join mode doesn't seem to work with taint tracking: https://github.com/returntocorp/semgrep/issues/5062

**Comment by christophetd** [comment]
Deprioritized / out of scope for now, especially considering join mode doesn't work with taint tracking.
