### ISSUE TITLE
Potentially incorrect find with cmd-override

### ISSUE THREAD

**Issue by maciejstromich** [DataDog/guarddog#77]
I'm a bit confused why guarddog reports pip command override in this case where the reads are clearly happening in the `long_description`. 
Package: pytest-cov version 4.0.0 
Link to code: https://github.com/pytest-dev/pytest-cov/blob/master/setup.py#L88)

```
cmd-overwrite: found 1 source code matches
  * Standard pip command overwritten in setup.py at pytest-cov-4.0.0/setup.py:88
        setup(
        name='pytest-cov',
        version='4.0.0',
        license='MIT',
        description='Pytest plugin for measuring coverage.',
        long_description='{}\n{}'.format(read('README.rst'), re.sub(':[a-z]+:`~?(.*?)`', r'``\1``', read('CHANGELOG.r...,
        },
    )
```

**Comment by christophetd** [comment]
Definitely a false positive. Thanks!

**Comment by christophetd** [comment]
So I checked and this is actually normal.

The `setup` call does define a custom install command later in the file: https://github.com/pytest-dev/pytest-cov/blob/master/setup.py#L152-L158

The way the code is being snipped in the GuardDog output isn't optimal, but then I think it would qualify as an enhancement and not a bug. I'll close for now but feel free to reopen if needed!
