### ISSUE TITLE
Avoid using strict version constraints in pyproject.yaml

### ISSUE THREAD

**Issue by AngellusMortis** [DataDog/guarddog#79]
Trying to integrate guarddog into our development toolkit and the fact that the [package pinning top level deps](https://github.com/DataDog/guarddog/blob/main/pyproject.toml#L11) makes it hard to integrate into existing environments. 

It would be great if these are changed to less restrictive modifiers so it can be install so the package does not need its own environment.

**Comment by christophetd** [comment]
Makes sense. So your suggestion would be to pin e.g. `python-dateutil = "==2.8"` instead of `python-dateutil = "==2.8.2"`?

**Comment by christophetd** [comment]
(happy to give it a try, but also feel free to send out a PR if you'd like to!)

**Comment by AngellusMortis** [comment]
No, remove the versions completely or add greater thans/less thans. 

The issue with exact versions for a package that is designed to be installed in another env as a tool/library is that it cannot have exact versions. Exact versions essentially makes super likely to have conflicting deps preventing install.

A good example (and what is happening for us) is you have a requirements.txt and a dev-requirements.txt. For prod/development reqs. If we already use dateutil in our prod requires, the chances of us using a _different_ version then guarddog is high mean we cannot add it to our dev-requirements.txt
