### ISSUE TITLE
Upload to PyPi

### ISSUE THREAD

**Issue by AngellusMortis** [DataDog/guarddog#80]
It would be nice if the package was uploaded to PyPi so it does not need to be installed directly from Github. 

* `guarddog @ git+https://github.com/DataDog/guarddog.git@v0.1.1` is a much longer dep then just `guarddog`
* Installing directly from github means a PyPi mirror cannot be used, meaning builds can be slowed down
* Another malicious package may get uploaded to PyPi that pretends to be this one

**Comment by quantumpacket** [comment]
> Another malicious package may get uploaded to PyPi that pretends to be this one

This!

**Comment by christophetd** [comment]
That's a good point. We'll be looking into it.

**Comment by christophetd** [comment]
While we get this sorted out I booked the package name with my personal account already. https://pypi.org/project/guarddog/

**Comment by christophetd** [comment]
WIP in #84

**Comment by christophetd** [comment]
Now published on PyPI: https://pypi.org/project/guarddog/

README updated as well!
