### ISSUE TITLE
potential false positive in potentially_compromised_email_domain

### ISSUE THREAD

**Issue by maciejstromich** [DataDog/guarddog#90]
```
Found 1 potentially malicious indicators in gunicorn version 20.1.0

potentially_compromised_email_domain: The domain name of the maintainer's email address was re-registered after the latest release of this package. This can be an indicator that this is a custom domain that expired, and was leveraged by an attacker to compromise the package owner's PyPi account.
```

as far as I can see this check is comparing the datetime of the defined package with the changes in the whois database (please correct me if I'm wrong because I spent like 5 minutes looking at this). What does domain re-registered mean in the context of this check? Can it also mean a simple domain extension? from the gunicorn's whois output I see
```
Updated Date: 2022-01-01T05:27:21Z
Creation Date: 2010-01-18T23:13:26Z
```
and the output doesn't indicate that the domain was re-registered.

**Comment by maciejstromich** [comment]
ah. my bad it's the maintainers email domain which in case of gunicorn is different 

https://github.com/benoitc/gunicorn/blob/master/setup.py#L95

and the whois output is correct
```
Updated Date: 2022-07-11 21:18:30
Creation Date: 2022-07-11 19:12:15
```
which is after the release date of the latest version of the package

**Comment by christophetd** [comment]
Thanks!
